export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const DETAIL_CUSTOMER = "DETAIL_CUSTOMER";
export const ADD_CUSTOMERS = "ADD_CUSTOMERS";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";

export const FETCH_STAFFS = "FETCH_STAFFS";
export const DETAIL_STAFF = "DETAIL_STAFF";
export const ADD_STAFF = "ADD_STAFF";
export const EDIT_STAFF = "EDIT_STAFF";

export const FECTH_COSTS = "FECTH_COSTS";

export const FETCH_CARRIERS = "FETCH_CARRIERS";
export const DETAIL_CARRIER = "DETAIL_CARRIER";
export const ADD_CARRIER = "ADD_CARRIER";
export const EDIT_CARRIER = "EDIT_CARRIER";

export const FETCH_AGENTS = "FETCH_AGENTS";
export const FETCH_GARAGES = "FETCH_GARAGES";
export const FETCH_BRANDS = "FETCH_BRANDS";

export const SEARCH = "SEARCH";
export const SEARCH_ALL = "SEARCH_ALL";

export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const EMPTY_DETAIL = "EMPTY_DETAIL";
export const EMPTY_DETAIL_JOB = "EMPTY_DETAIL_JOB";

export const FETCH_PAYMENTS = "FETCH_PAYMENTS";
export const DETAIL_PAYMENT = "DETAIL_PAYMENT";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const EDIT_PAYMENT = "EDIT_PAYMENT";

export const FETCH_JOBS = "FETCH_JOBS";
export const DETAIL_JOB = "DETAIL_JOB";
export const ADD_JOB = "ADD_JOB";
export const EDIT_JOB = "EDIT_JOB";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL_EDIT = "OPEN_MODAL_EDIT";

export const JOB_NOT_CREATE_ORDER = "JOB_NOT_CREATE_ORDER";
export const DETAIL_JOB_NOT_CREATE_ORDER = "DETAIL_JOB_NOT_CREATE_ORDER";

export const ADD_JOB_ORDER = "ADD_JOB_ORDER";
export const JOB_ORDER = "JOB_ORDER";

export const LIST_PENDING = "LIST_PENDING";
export const LIST_APPROVED = "LIST_APPROVED";

export const APPROVED = 'APPROVED'
export const ITEM_JOB_PAYMENT = 'ITEM_JOB_PAYMENT'
export const EMPTY_ITEM_JOB_PAYMENT = 'EMPTY_ITEM_JOB_PAYMENT'